
package me.savushkin.wst;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import java.util.List;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 */
@WebService(name = "MusicAlbumWebService", targetNamespace = "http://wst.savushkin.me/")
@XmlSeeAlso({
        ObjectFactory.class
})
public interface MusicAlbumWebService {


    /**
     * @return returns java.util.List<me.savushkin.wst.MusicAlbum>
     */
    @WebMethod(operationName = "get-albums")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "get-albums", targetNamespace = "http://wst.savushkin.me/", className = "me.savushkin.wst.GetAlbums")
    @ResponseWrapper(localName = "get-albumsResponse", targetNamespace = "http://wst.savushkin.me/", className = "me.savushkin.wst.GetAlbumsResponse")
    List<MusicAlbum> getAlbums();

    /**
     * @param trackCount
     * @param artist
     * @param genre
     * @param title
     * @param releaseYear
     * @return returns java.util.List<me.savushkin.wst.MusicAlbum>
     */
    @WebMethod(operationName = "find-albums")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "find-albums", targetNamespace = "http://wst.savushkin.me/", className = "me.savushkin.wst.FindAlbums")
    @ResponseWrapper(localName = "find-albumsResponse", targetNamespace = "http://wst.savushkin.me/", className = "me.savushkin.wst.FindAlbumsResponse")
    List<MusicAlbum> findAlbums(
            @WebParam(name = "title", targetNamespace = "")
                    String title,
            @WebParam(name = "artist", targetNamespace = "")
                    String artist,
            @WebParam(name = "releaseYear", targetNamespace = "")
                    Long releaseYear,
            @WebParam(name = "genre", targetNamespace = "")
                    String genre,
            @WebParam(name = "trackCount", targetNamespace = "")
                    Long trackCount);

}
