
package me.savushkin.wst.lab2;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import java.util.List;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 */
@WebService(name = "MusicAlbumWebService", targetNamespace = "http://lab2.wst.savushkin.me/")
@XmlSeeAlso({
        ObjectFactory.class
})
public interface MusicAlbumWebService {


    /**
     * @param trackCount
     * @param artist
     * @param genre
     * @param id
     * @param title
     * @param releaseYear
     * @return returns java.lang.String
     */
    @WebMethod(operationName = "update-album")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "update-album", targetNamespace = "http://lab2.wst.savushkin.me/", className = "me.savushkin.wst.lab2.UpdateAlbum")
    @ResponseWrapper(localName = "update-albumResponse", targetNamespace = "http://lab2.wst.savushkin.me/", className = "me.savushkin.wst.lab2.UpdateAlbumResponse")
    @Action(input = "http://lab2.wst.savushkin.me/MusicAlbumWebService/update-albumRequest", output = "http://lab2.wst.savushkin.me/MusicAlbumWebService/update-albumResponse")
    public String updateAlbum(
            @WebParam(name = "id", targetNamespace = "")
                    Long id,
            @WebParam(name = "title", targetNamespace = "")
                    String title,
            @WebParam(name = "artist", targetNamespace = "")
                    String artist,
            @WebParam(name = "releaseYear", targetNamespace = "")
                    Long releaseYear,
            @WebParam(name = "genre", targetNamespace = "")
                    String genre,
            @WebParam(name = "trackCount", targetNamespace = "")
                    Long trackCount);

    /**
     * @param id
     * @return returns java.lang.String
     */
    @WebMethod(operationName = "delete-album")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "delete-album", targetNamespace = "http://lab2.wst.savushkin.me/", className = "me.savushkin.wst.lab2.DeleteAlbum")
    @ResponseWrapper(localName = "delete-albumResponse", targetNamespace = "http://lab2.wst.savushkin.me/", className = "me.savushkin.wst.lab2.DeleteAlbumResponse")
    @Action(input = "http://lab2.wst.savushkin.me/MusicAlbumWebService/delete-albumRequest", output = "http://lab2.wst.savushkin.me/MusicAlbumWebService/delete-albumResponse")
    public String deleteAlbum(
            @WebParam(name = "id", targetNamespace = "")
                    Long id);

    /**
     * @param trackCount
     * @param artist
     * @param genre
     * @param title
     * @param releaseYear
     * @return returns java.lang.String
     */
    @WebMethod(operationName = "create-album")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "create-album", targetNamespace = "http://lab2.wst.savushkin.me/", className = "me.savushkin.wst.lab2.CreateAlbum")
    @ResponseWrapper(localName = "create-albumResponse", targetNamespace = "http://lab2.wst.savushkin.me/", className = "me.savushkin.wst.lab2.CreateAlbumResponse")
    @Action(input = "http://lab2.wst.savushkin.me/MusicAlbumWebService/create-albumRequest", output = "http://lab2.wst.savushkin.me/MusicAlbumWebService/create-albumResponse")
    public String createAlbum(
            @WebParam(name = "title", targetNamespace = "")
                    String title,
            @WebParam(name = "artist", targetNamespace = "")
                    String artist,
            @WebParam(name = "releaseYear", targetNamespace = "")
                    Long releaseYear,
            @WebParam(name = "genre", targetNamespace = "")
                    String genre,
            @WebParam(name = "trackCount", targetNamespace = "")
                    Long trackCount);

    /**
     * @param trackCount
     * @param artist
     * @param genre
     * @param title
     * @param releaseYear
     * @return returns java.util.List<me.savushkin.wst.lab2.MusicAlbum>
     */
    @WebMethod(operationName = "find-albums")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "find-albums", targetNamespace = "http://lab2.wst.savushkin.me/", className = "me.savushkin.wst.lab2.FindAlbums")
    @ResponseWrapper(localName = "find-albumsResponse", targetNamespace = "http://lab2.wst.savushkin.me/", className = "me.savushkin.wst.lab2.FindAlbumsResponse")
    @Action(input = "http://lab2.wst.savushkin.me/MusicAlbumWebService/find-albumsRequest", output = "http://lab2.wst.savushkin.me/MusicAlbumWebService/find-albumsResponse")
    public List<MusicAlbum> findAlbums(
            @WebParam(name = "title", targetNamespace = "")
                    String title,
            @WebParam(name = "artist", targetNamespace = "")
                    String artist,
            @WebParam(name = "releaseYear", targetNamespace = "")
                    Long releaseYear,
            @WebParam(name = "genre", targetNamespace = "")
                    String genre,
            @WebParam(name = "trackCount", targetNamespace = "")
                    Long trackCount);

    /**
     * @return returns java.util.List<me.savushkin.wst.lab2.MusicAlbum>
     */
    @WebMethod(operationName = "get-albums")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "get-albums", targetNamespace = "http://lab2.wst.savushkin.me/", className = "me.savushkin.wst.lab2.GetAlbums")
    @ResponseWrapper(localName = "get-albumsResponse", targetNamespace = "http://lab2.wst.savushkin.me/", className = "me.savushkin.wst.lab2.GetAlbumsResponse")
    @Action(input = "http://lab2.wst.savushkin.me/MusicAlbumWebService/get-albumsRequest", output = "http://lab2.wst.savushkin.me/MusicAlbumWebService/get-albumsResponse")
    public List<MusicAlbum> getAlbums();

}
