
package me.savushkin.wst.lab3;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 */
@WebFault(name = "WSTException", targetNamespace = "http://lab3.wst.savushkin.me/")
public class WSTException
        extends Exception {

    /**
     * Java type that goes as soapenv:Fault detail element.
     */
    private WstFaultException faultInfo;

    /**
     * @param faultInfo
     * @param message
     */
    public WSTException(String message, WstFaultException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * @param faultInfo
     * @param cause
     * @param message
     */
    public WSTException(String message, WstFaultException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * @return returns fault bean: me.savushkin.wst.lab3.WstFaultException
     */
    public WstFaultException getFaultInfo() {
        return faultInfo;
    }

}
